"""
hmm_predictor.py
================

Production-grade Hidden Markov Model (HMM) wrapper for financial time-series
regime detection and short-horizon forecasting, designed to plug into a
web backend (Flask / FastAPI / Django).

--------------------------------------------------------------------------
MATHEMATICAL BACKGROUND & MODELLING ASSUMPTIONS
--------------------------------------------------------------------------
A Gaussian Hidden Markov Model assumes that an observed time series
``O = (o_1, ..., o_T)`` is generated by an *unobserved* (hidden) Markov chain
of discrete states ``S = (s_1, ..., s_T)``, with ``s_t in {1, ..., K}``.

The model is fully specified by ``lambda = (pi, A, B)``:

    * pi  : initial state distribution,           pi_i  = P(s_1 = i)
    * A   : state transition matrix,              A_ij  = P(s_t = j | s_{t-1} = i)
    * B   : emission distributions. For a Gaussian HMM each state ``i`` emits
            observations from a multivariate normal  N(mu_i, Sigma_i).

Core assumptions you are implicitly accepting when you use this class:

    1. Markov property (first order): the next hidden state depends only on
       the current state, not the full history -- P(s_t | s_{1:t-1}) = P(s_t | s_{t-1}).
    2. Conditional independence of emissions: given the hidden state, the
       observation is independent of everything else.
    3. (Quasi) stationarity: pi, A and B are time-invariant over the training
       window. In markets this is only *locally* true, so models must be
       periodically re-fit on rolling windows. Treat a fitted model as valid
       only for a regime similar to the one it was trained on.
    4. Gaussian emissions: returns within a regime are approximately normal.
       This is why we model *returns* (and standardise them), not raw prices.

Training uses the Baum-Welch algorithm, which is a specialisation of
Expectation-Maximisation (EM):

    * E-step: using the current parameter estimate, compute the posterior
      probabilities of the hidden states (the "responsibilities") via the
      forward-backward algorithm.
    * M-step: re-estimate pi, A and the Gaussian emission parameters
      (means / covariances) to maximise the expected complete-data
      log-likelihood under those responsibilities.

EM only guarantees convergence to a *local* optimum and is sensitive to
initial parameters; this module therefore supports K-Means initialisation of
the emission means to obtain more stable, reproducible fits.

Decoding the single most likely hidden-state path is done with the Viterbi
algorithm (a max-product dynamic program), exposed via ``predict_hidden_states``.

--------------------------------------------------------------------------
NUMERICAL STABILITY NOTES (READ BEFORE FEEDING DATA IN)
--------------------------------------------------------------------------
Raw prices are non-stationary, trending and on wildly different scales across
assets. Feeding them directly into a Gaussian HMM causes:

    * floating-point underflow in the forward-backward recursions, and
    * near-singular / ill-conditioned covariance matrices in the M-step.

Recommended pre-processing pipeline (see ``HMMPredictor.fit`` docstring):

    1. Convert prices to *log returns*:  r_t = log(P_t) - log(P_{t-1}).
       This de-trends the series and makes it closer to stationary.
    2. Standardise each feature to zero mean / unit variance. This class does
       the scaling internally with a ``StandardScaler`` and persists the scaler
       parameters, so prediction-time inputs are transformed identically.
    3. Optionally winsorise extreme outliers before fitting if your asset has
       fat tails, to stop a handful of jumps dominating the covariance.

The class adds a small ``min_covar`` floor to the covariance diagonal to guard
against singular covariance matrices.
"""

from __future__ import annotations

import json
import logging
import warnings
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import pandas as pd

try:
    from hmmlearn.hmm import GaussianHMM
except ImportError as exc:  # pragma: no cover - dependency guard
    raise ImportError(
        "hmmlearn is required. Install it with `pip install hmmlearn`."
    ) from exc

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

logger = logging.getLogger(__name__)

# Public schema version for serialised models. Bump on breaking format changes.
MODEL_SCHEMA_VERSION = "1.0"

ArrayLike = Union[np.ndarray, pd.DataFrame, pd.Series, Sequence[float]]


class HMMError(Exception):
    """Base exception for all HMMPredictor failures."""


class ConvergenceError(HMMError):
    """Raised when the EM (Baum-Welch) algorithm fails to converge."""


class SingularCovarianceError(HMMError):
    """Raised when an emission covariance matrix is singular / non-positive-definite."""


class NotFittedError(HMMError):
    """Raised when prediction is attempted before the model has been fitted."""


class HMMPredictor:
    """
    A configurable, serialisable Gaussian-HMM wrapper for regime detection
    and short-horizon probabilistic forecasting of financial time series.

    Parameters
    ----------
    n_components : int, default 3
        Number of hidden states (regimes), e.g. bull / sideways / bear.
    covariance_type : {'full', 'tied', 'diag', 'spherical'}, default 'diag'
        Structure of the per-state covariance matrices. 'diag' is the most
        robust default for financial data (fewer parameters, less prone to
        singularity); 'full' captures cross-feature correlation at the cost of
        more data and stability.
    n_iter : int, default 100
        Maximum number of EM iterations.
    tol : float, default 1e-4
        Convergence threshold on the log-likelihood gain between iterations.
    min_covar : float, default 1e-3
        Floor added to the covariance diagonal to prevent singular matrices.
    init_method : {'kmeans', 'random'}, default 'kmeans'
        Strategy for initialising emission means. K-Means initialisation makes
        the EM fit far more reproducible and is strongly recommended.
    random_state : int, optional
        Seed for reproducible fits.
    verbose : bool, default False
        Forwarded to the underlying hmmlearn model for per-iteration logging.

    Notes
    -----
    The estimator follows the scikit-learn convention: states are 0-indexed
    and there is no inherent ordering. If you need a stable "regime 0 = lowest
    mean return" mapping for a UI, sort states by ``means_`` after fitting.
    """

    _VALID_COVARIANCE_TYPES = ("full", "tied", "diag", "spherical")
    _VALID_INIT_METHODS = ("kmeans", "random")

    def __init__(
        self,
        n_components: int = 3,
        covariance_type: str = "diag",
        n_iter: int = 100,
        tol: float = 1e-4,
        min_covar: float = 1e-3,
        init_method: str = "kmeans",
        random_state: Optional[int] = 42,
        verbose: bool = False,
    ) -> None:
        # ---- configuration validation ------------------------------------
        if not isinstance(n_components, int) or n_components < 1:
            raise ValueError("n_components must be a positive integer.")
        if covariance_type not in self._VALID_COVARIANCE_TYPES:
            raise ValueError(
                f"covariance_type must be one of {self._VALID_COVARIANCE_TYPES}, "
                f"got {covariance_type!r}."
            )
        if init_method not in self._VALID_INIT_METHODS:
            raise ValueError(
                f"init_method must be one of {self._VALID_INIT_METHODS}, "
                f"got {init_method!r}."
            )
        if not isinstance(n_iter, int) or n_iter < 1:
            raise ValueError("n_iter must be a positive integer.")

        self.n_components = n_components
        self.covariance_type = covariance_type
        self.n_iter = n_iter
        self.tol = tol
        self.min_covar = min_covar
        self.init_method = init_method
        self.random_state = random_state
        self.verbose = verbose

        # ---- learned state (populated by fit / load) ---------------------
        self.model: Optional[GaussianHMM] = None
        self.scaler: Optional[StandardScaler] = None
        self.n_features_: Optional[int] = None
        self.feature_names_: Optional[List[str]] = None
        self.converged_: bool = False
        self.score_: Optional[float] = None
        self.fitted_at_: Optional[str] = None

    # ======================================================================
    # Input handling
    # ======================================================================
    def _coerce_input(
        self, data: ArrayLike
    ) -> Tuple[np.ndarray, Optional[List[str]]]:
        """
        Convert supported input types into a clean 2D float array of shape
        (n_samples, n_features) and validate it.

        Raises
        ------
        ValueError
            If the data is empty, contains NaN/inf, or has the wrong dimensions.
        """
        feature_names: Optional[List[str]] = None

        if isinstance(data, pd.DataFrame):
            feature_names = list(map(str, data.columns))
            arr = data.to_numpy(dtype=float)
        elif isinstance(data, pd.Series):
            feature_names = [str(data.name)] if data.name is not None else None
            arr = data.to_numpy(dtype=float).reshape(-1, 1)
        else:
            arr = np.asarray(data, dtype=float)
            if arr.ndim == 1:
                arr = arr.reshape(-1, 1)

        if arr.ndim != 2:
            raise ValueError(
                f"Expected 2D data (n_samples, n_features), got shape {arr.shape}."
            )
        if arr.size == 0:
            raise ValueError("Input data is empty.")
        if not np.all(np.isfinite(arr)):
            raise ValueError(
                "Input contains NaN or infinite values. Clean the series "
                "(e.g. dropna / forward-fill) before fitting or predicting."
            )
        return arr, feature_names

    # ======================================================================
    # Initialisation helpers
    # ======================================================================
    def _build_model(self, X: np.ndarray) -> GaussianHMM:
        """Construct a GaussianHMM, optionally seeding means via K-Means."""
        # 's' = startprob, 't' = transmat, 'm' = means, 'c' = covars.
        # When we supply means via K-Means we drop 'm' from init_params so
        # hmmlearn does not overwrite our seed.
        init_params = "stmc"
        model = GaussianHMM(
            n_components=self.n_components,
            covariance_type=self.covariance_type,
            n_iter=self.n_iter,
            tol=self.tol,
            min_covar=self.min_covar,
            random_state=self.random_state,
            verbose=self.verbose,
        )

        if self.init_method == "kmeans" and X.shape[0] >= self.n_components:
            km = KMeans(
                n_clusters=self.n_components,
                random_state=self.random_state,
                n_init=10,
            )
            km.fit(X)
            model.means_ = km.cluster_centers_
            init_params = init_params.replace("m", "")

        model.init_params = init_params
        return model

    # ======================================================================
    # Training
    # ======================================================================
    def fit(self, data: ArrayLike) -> "HMMPredictor":
        """
        Validate, scale and train the HMM on a time series.

        Parameters
        ----------
        data : array-like, DataFrame or Series of shape (n_samples, n_features)
            The observation sequence. **Pass stationary features** (e.g. log
            returns), not raw prices. Scaling to zero-mean/unit-variance is
            performed internally and the scaler is persisted, so you do *not*
            need to standardise before calling fit -- but you *do* need to
            convert prices to returns yourself, for example::

                log_ret = np.diff(np.log(prices))
                predictor.fit(log_ret)

        Returns
        -------
        self

        Raises
        ------
        ConvergenceError
            If EM does not reach the convergence tolerance within ``n_iter``.
        SingularCovarianceError
            If an emission covariance becomes singular / non-positive-definite.
        ValueError
            If the input fails validation.
        """
        X, feature_names = self._coerce_input(data)

        # Standardise features -> numerical stability for forward-backward.
        self.scaler = StandardScaler()
        X_scaled = self.scaler.fit_transform(X)

        self.n_features_ = X_scaled.shape[1]
        self.feature_names_ = feature_names or [
            f"feature_{i}" for i in range(self.n_features_)
        ]

        model = self._build_model(X_scaled)

        # Capture hmmlearn convergence warnings and turn linalg failures into
        # explicit, catchable exceptions for the web layer.
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            try:
                model.fit(X_scaled)
            except (np.linalg.LinAlgError, ValueError) as exc:
                msg = str(exc).lower()
                if "singular" in msg or "positive" in msg or "covar" in msg:
                    raise SingularCovarianceError(
                        "Emission covariance matrix is singular. Try "
                        "covariance_type='diag' or 'spherical', increase "
                        "min_covar, or supply more / less collinear data."
                    ) from exc
                raise

            converged = bool(getattr(model.monitor_, "converged", False))
            if any("converge" in str(w.message).lower() for w in caught):
                converged = False

        if not converged:
            raise ConvergenceError(
                f"EM failed to converge in n_iter={self.n_iter}. Increase "
                f"n_iter, relax tol, reduce n_components, or provide more data."
            )

        # Defensive covariance check (covers cases hmmlearn does not raise on).
        self._validate_covariances(model)

        self.model = model
        self.converged_ = True
        self.score_ = float(model.score(X_scaled))
        self.fitted_at_ = datetime.now(timezone.utc).isoformat()
        logger.info(
            "HMM fitted: %d states, covariance_type=%s, logL=%.4f",
            self.n_components,
            self.covariance_type,
            self.score_,
        )
        return self

    def _validate_covariances(self, model: GaussianHMM) -> None:
        """Ensure every per-state covariance is positive-definite."""
        covars = model.covars_  # always returned as (n_components, n_feat, n_feat)
        for i, cov in enumerate(np.atleast_3d(covars)):
            try:
                np.linalg.cholesky(cov)
            except np.linalg.LinAlgError as exc:
                raise SingularCovarianceError(
                    f"Covariance for state {i} is not positive-definite. "
                    f"Increase min_covar or use a simpler covariance_type."
                ) from exc

    # ======================================================================
    # Decoding / inference
    # ======================================================================
    def _check_fitted(self) -> None:
        if self.model is None or self.scaler is None:
            raise NotFittedError("Model is not fitted. Call fit() or load() first.")

    def predict_hidden_states(self, data: ArrayLike) -> np.ndarray:
        """
        Decode the most likely sequence of hidden states with the Viterbi
        algorithm.

        Parameters
        ----------
        data : array-like of shape (n_samples, n_features)
            New observations in the *same feature space* used at fit time
            (e.g. log returns). They are scaled with the persisted scaler.

        Returns
        -------
        np.ndarray of shape (n_samples,)
            The 0-indexed hidden state assigned to each timestep.
        """
        self._check_fitted()
        X, _ = self._coerce_input(data)
        self._check_feature_dim(X)
        X_scaled = self.scaler.transform(X)
        # algorithm='viterbi' is hmmlearn's default; stated explicitly here.
        _, states = self.model.decode(X_scaled, algorithm="viterbi")
        return states

    def predict_state_proba(self, data: ArrayLike) -> np.ndarray:
        """
        Posterior probability of each hidden state at each timestep
        (forward-backward / smoothing), shape (n_samples, n_components).

        Useful for a UI that shades regime *confidence* rather than a hard
        Viterbi assignment.
        """
        self._check_fitted()
        X, _ = self._coerce_input(data)
        self._check_feature_dim(X)
        X_scaled = self.scaler.transform(X)
        return self.model.predict_proba(X_scaled)

    def _check_feature_dim(self, X: np.ndarray) -> None:
        if self.n_features_ is not None and X.shape[1] != self.n_features_:
            raise ValueError(
                f"Expected {self.n_features_} feature(s), got {X.shape[1]}."
            )

    # ======================================================================
    # Forecasting
    # ======================================================================
    def forecast_next(
        self, data: ArrayLike, n_steps: int = 1
    ) -> Dict[str, Any]:
        """
        Forecast the hidden-state distribution and expected observation for the
        next ``n_steps`` timesteps.

        Method
        ------
        1. Smooth the supplied history to obtain the posterior over the current
           hidden state, ``gamma_T = P(s_T | o_{1:T})``.
        2. Propagate it forward through the transition matrix:
           ``gamma_{T+k} = gamma_T @ A^k``.
        3. The expected (scaled) observation at step T+k is the state-probability
           weighted mixture of emission means; we inverse-transform it back to
           the original feature space for human-readable output.

        Parameters
        ----------
        data : array-like
            The observed history used to anchor the forecast.
        n_steps : int, default 1
            Forecast horizon.

        Returns
        -------
        dict
            {
              "horizon": int,
              "current_state_distribution": [...],          # P(s_T | o_{1:T})
              "forecast": [
                 {
                   "step": 1,
                   "state_distribution": [...],             # sums to 1
                   "expected_observation": [...],           # original units
                 }, ...
              ]
            }
        """
        self._check_fitted()
        if not isinstance(n_steps, int) or n_steps < 1:
            raise ValueError("n_steps must be a positive integer.")

        X, _ = self._coerce_input(data)
        self._check_feature_dim(X)
        X_scaled = self.scaler.transform(X)

        # Posterior over the most recent state.
        gamma = self.model.predict_proba(X_scaled)[-1]  # shape (n_components,)
        A = self.model.transmat_
        means_scaled = self.model.means_  # (n_components, n_features)

        forecasts: List[Dict[str, Any]] = []
        dist = gamma.copy()
        for step in range(1, n_steps + 1):
            dist = dist @ A  # one-step-ahead state propagation
            expected_scaled = dist @ means_scaled  # weighted emission mean
            expected_original = self.scaler.inverse_transform(
                expected_scaled.reshape(1, -1)
            ).ravel()
            forecasts.append(
                {
                    "step": step,
                    "state_distribution": dist.tolist(),
                    "expected_observation": expected_original.tolist(),
                }
            )

        return {
            "horizon": n_steps,
            "current_state_distribution": gamma.tolist(),
            "forecast": forecasts,
        }

    # ======================================================================
    # Serialisation (JSON) -- keeps the web backend lightweight
    # ======================================================================
    def to_dict(self) -> Dict[str, Any]:
        """
        Export all learned parameters to a plain (JSON-serialisable) dict.

        Persisting *parameters* (not a pickled object) means the web service
        loads a few KB of JSON and reconstructs the model in milliseconds,
        instead of re-running an expensive ``fit`` per request. Pickle is also
        avoided for security and cross-version portability.
        """
        self._check_fitted()
        return {
            "schema_version": MODEL_SCHEMA_VERSION,
            "fitted_at": self.fitted_at_,
            "config": {
                "n_components": self.n_components,
                "covariance_type": self.covariance_type,
                "n_iter": self.n_iter,
                "tol": self.tol,
                "min_covar": self.min_covar,
                "init_method": self.init_method,
                "random_state": self.random_state,
            },
            "metadata": {
                "n_features": self.n_features_,
                "feature_names": self.feature_names_,
                "converged": self.converged_,
                "log_likelihood": self.score_,
            },
            "scaler": {
                "mean": self.scaler.mean_.tolist(),
                "scale": self.scaler.scale_.tolist(),
            },
            "parameters": {
                "startprob": self.model.startprob_.tolist(),
                "transmat": self.model.transmat_.tolist(),
                "means": self.model.means_.tolist(),
                # covars_ is normalised to (n_components, n_feat, n_feat).
                "covars": np.atleast_3d(self.model.covars_).tolist(),
            },
        }

    def save(self, path: str) -> None:
        """Write the serialised model parameters to a JSON file on disk."""
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2)
        logger.info("Model parameters saved to %s", path)

    def to_json(self) -> str:
        """Return the serialised model as a JSON string (e.g. to store in a DB)."""
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "HMMPredictor":
        """
        Reconstruct a ready-to-predict HMMPredictor from a parameter dict
        produced by ``to_dict``. No training is performed.
        """
        version = payload.get("schema_version")
        if version != MODEL_SCHEMA_VERSION:
            logger.warning(
                "Loading model with schema_version=%s (current=%s). "
                "Proceeding, but verify compatibility.",
                version,
                MODEL_SCHEMA_VERSION,
            )

        cfg = payload["config"]
        instance = cls(
            n_components=cfg["n_components"],
            covariance_type=cfg["covariance_type"],
            n_iter=cfg["n_iter"],
            tol=cfg["tol"],
            min_covar=cfg["min_covar"],
            init_method=cfg["init_method"],
            random_state=cfg["random_state"],
        )

        meta = payload.get("metadata", {})
        instance.n_features_ = meta.get("n_features")
        instance.feature_names_ = meta.get("feature_names")
        instance.converged_ = meta.get("converged", True)
        instance.score_ = meta.get("log_likelihood")
        instance.fitted_at_ = payload.get("fitted_at")

        # Rebuild the scaler.
        scaler = StandardScaler()
        scaler.mean_ = np.asarray(payload["scaler"]["mean"], dtype=float)
        scaler.scale_ = np.asarray(payload["scaler"]["scale"], dtype=float)
        scaler.var_ = scaler.scale_ ** 2
        scaler.n_features_in_ = scaler.mean_.shape[0]
        instance.scaler = scaler

        # Rebuild the HMM and inject the learned parameters.
        params = payload["parameters"]
        model = GaussianHMM(
            n_components=cfg["n_components"],
            covariance_type=cfg["covariance_type"],
        )
        model.startprob_ = np.asarray(params["startprob"], dtype=float)
        model.transmat_ = np.asarray(params["transmat"], dtype=float)
        model.means_ = np.asarray(params["means"], dtype=float)

        covars_full = np.asarray(params["covars"], dtype=float)
        # hmmlearn expects covars_ in a packed shape depending on covariance_type.
        model.covars_ = cls._pack_covars(covars_full, cfg["covariance_type"])
        instance.model = model
        return instance

    @staticmethod
    def _pack_covars(covars_full: np.ndarray, covariance_type: str) -> np.ndarray:
        """
        Convert the full (n_components, n_feat, n_feat) covariance tensor back
        into the representation hmmlearn stores internally for each
        covariance_type.
        """
        if covariance_type == "full":
            return covars_full
        if covariance_type == "tied":
            return covars_full[0]
        if covariance_type == "diag":
            return np.array([np.diag(c) for c in covars_full])
        if covariance_type == "spherical":
            return np.array([np.diag(c).mean() for c in covars_full])
        raise ValueError(f"Unknown covariance_type {covariance_type!r}.")

    @classmethod
    def load(cls, path: str) -> "HMMPredictor":
        """Load a model from a JSON file written by ``save``."""
        with open(path, "r", encoding="utf-8") as fh:
            payload = json.load(fh)
        return cls.from_dict(payload)

    @classmethod
    def from_json(cls, text: str) -> "HMMPredictor":
        """Load a model from a JSON string (e.g. fetched from a DB)."""
        return cls.from_dict(json.loads(text))

    # ======================================================================
    # Convenience: a front-end-friendly summary payload
    # ======================================================================
    def api_summary(self, data: ArrayLike, n_steps: int = 3) -> Dict[str, Any]:
        """
        Build a single JSON-serialisable payload tailored for a dashboard:
        the decoded regime per timestep, posterior confidences, and a forward
        forecast. See README / example_usage.py for the documented schema.
        """
        self._check_fitted()
        states = self.predict_hidden_states(data)
        proba = self.predict_state_proba(data)
        forecast = self.forecast_next(data, n_steps=n_steps)
        return {
            "schema_version": MODEL_SCHEMA_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "n_components": self.n_components,
            "feature_names": self.feature_names_,
            "states": states.tolist(),
            "state_probabilities": proba.tolist(),
            "forecast": forecast,
        }

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        status = "fitted" if self.model is not None else "unfitted"
        return (
            f"HMMPredictor(n_components={self.n_components}, "
            f"covariance_type={self.covariance_type!r}, status={status})"
        )
